services:
  kafka:
    image: confluentinc/confluent-local:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Single-node KRaft mode (no Zookeeper)
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  kafka_data:




#version: "3.8"
#
#services:
#  kafka:
#    image: confluentinc/confluent-local:latest
#    container_name: kafka
#    networks:
#      - shared-net
#    ports:
#      - "9092:9092"   # internal broker listener
#      - "9094:9094"   # external listener for host clients
#    environment:
#      KAFKA_ENABLE_KRAFT: yes
#      KAFKA_CFG_NODE_ID: 1
#      KAFKA_CFG_PROCESS_ROLES: broker,controller
#
#      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
#
#      # Multiple listeners: internal and external
#      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
#      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
#      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
#
#      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
#      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      ALLOW_PLAINTEXT_LISTENER: yes
#
#volumes:
#  kafka_data:
#
#networks:
#  shared-net:
#    external: true

#version: "3.8"
#
#services:
#  kafka:
#    image: confluentinc/confluent-local:latest
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      # Single-node KRaft mode (no Zookeeper)
#      KAFKA_ENABLE_KRAFT: yes
#      KAFKA_CFG_NODE_ID: 1
#      KAFKA_CFG_PROCESS_ROLES: broker,controller
#      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
#      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
#      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      ALLOW_PLAINTEXT_LISTENER: yes
#    volumes:
#      - kafka_data:/bitnami/kafka
#
#volumes:
#  kafka_data:
