version: "3.8"

services:
  kafka:
    image: confluentinc/confluent-local:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Single-node KRaft mode (no Zookeeper)
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  kafka_data:


# docker-compose.consumer.yml


#services:
#  consumer:
#    image: confluentinc/confluent-local:latest
#    environment:
#      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    ports:
#      - "8081:8081"
