server:
  port: 8081

spring:
  application:
    name: feedback-analytics-consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: feedback-analytics-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.Group2.feedback_analytics_consumer.model.FeedbackResponseDTO
        spring.json.use.type.headers: false   # ignore type headers from producer



#server:
#  port: 8082
#
#spring:
#  application:
#    name: feedback-analytics-consumer
#  kafka:
#    bootstrap-servers: kafka:9092
#    consumer:
#      group-id: feedback-analytics-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: com.Group2.feedback_analytics_consumer.model.FeedbackResponseDTO
#        spring.json.use.type.headers: false   # ignore type headers from producer
#


